In [1]:
import numpy as np

In [4]:
A = np.random.randint(0, 4, (2, 2))
B = np.random.randint(0, 4, (2, 2))


print(A + B)
print(A - B)
print(5 * B)

[[2 6]
 [5 6]]
[[-2  0]
 [ 1  0]]
[[10 15]
 [10 15]]


In [15]:
A = np.arange(1, 5, 1).reshape(2,2)
B = A.copy() + 4

print(A.dot(B))
print(B.dot(A))

print(np.array_equal(A.dot(B), B.dot(A)))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]
False


In [26]:
A = np.array([[3, 0], [-1, 2], [1, 1]])
B = np.array([[-3, -1], [2, 1], [4, 3]])
C = np.array([[1, 2, 3], [2, 0, 1]])
D = np.arange(1, 4).reshape((3, 1))

print(A + 2 * B)
print(np.matmul(A, C))
print(3 * D)

[[-3 -2]
 [ 3  4]
 [ 9  7]]
[[ 3  6  9]
 [ 3 -2 -1]
 [ 3  2  4]]
[[3]
 [6]
 [9]]
