In [2]:
import numpy as np

In [5]:
A = np.array([[2, 3], [5, 7]])

A_inv = np.linalg.inv(A)

print(A_inv)

[[-7.  3.]
 [ 5. -2.]]


In [6]:
b = np.array([[1, 3, 2], [2, 2, 0], [-3, 1, 1]])

print(np.linalg.inv(b))

[[ 0.16666667 -0.08333333 -0.33333333]
 [-0.16666667  0.58333333  0.33333333]
 [ 0.66666667 -0.83333333 -0.33333333]]


In [8]:
a = np.array([[-1, 3], [3, 7]])
a_t = a.T

print(a_t)

b = np.array([[1, 3, 5], [7, 2, 9], [10, 11, 3]])
b_t = b.T

print(b_t)

[[-1  3]
 [ 3  7]]
[[ 1  7 10]
 [ 3  2 11]
 [ 5  9  3]]
