In [2]:
import numpy as np
from sympy import *

In [3]:
a = np.array([[1, 3, 2], [2, 2, 0], [-3, 1, 1]])
b = np.array([[2, 0, -2]])

augmented_a = Matrix(np.hstack((a, b.T)))
print(np.array(augmented_a))
print(np.array(augmented_a.rref()[0]))

[[1 3 2 2]
 [2 2 0 0]
 [-3 1 1 -2]]
[[1 0 0 1]
 [0 1 0 -1]
 [0 0 1 2]]


In [4]:
a = np.array([[3, 6, 3], [2, 1, 4], [-1, 3, 5]])
b = np.array([[6, -1, -3]])

augmented_a = Matrix(np.hstack((a, b.T)))
print(np.array(augmented_a))
print(np.array(augmented_a.rref()[0]))

[[3 6 3 6]
 [2 1 4 -1]
 [-1 3 5 -3]]
[[1 0 0 1]
 [0 1 0 1]
 [0 0 1 -1]]
