In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sympy import *

In [ ]:
print(1.2e5, type(1.2e5))
print(1e-3, type(1e-3))

120000.0 <class 'float'>
0.001 <class 'float'>


In [7]:
import math

print(math.sqrt(2))
print(math.exp(3))
print(math.log(5))
print(math.cos(math.pi))
print(math.sin(math.pi / 2))
print(math.tan(math.pi / 4))

1.4142135623730951
20.085536923187668
1.6094379124341003
-1.0
1.0
0.9999999999999999


In [156]:
a = np.random.randint(0, 10, (10, 10))

print(a)

print(a[1][2])

[[0 7 9 0 6 0 7 6 5 3]
 [0 0 6 7 9 9 1 0 8 3]
 [8 4 5 7 5 1 0 4 2 3]
 [6 3 0 7 8 6 2 7 2 8]
 [5 7 9 3 4 7 6 8 6 5]
 [1 9 7 8 8 0 5 4 2 3]
 [9 5 8 2 2 7 5 6 2 5]
 [5 2 0 1 4 6 9 5 9 9]
 [7 1 8 1 0 7 0 8 0 0]
 [6 6 9 1 0 7 3 9 6 0]]
6


In [ ]:
a = a.flatten()

