In [1]:
import numpy as np
from dezero import Variable

In [2]:
import dezero.functions as F

a = np.array([[1, 3, 2], [3, 4, 6], [3, 4, 2], [1, 0, 0], [0, 0, 1]])
b = np.array([[1, 0, 0, 1], [0, 1, 0, 2], [0, 0, 1, 3]])

c = F.matmul(a, b)

print(c)

variable([[ 1  3  2 13]
          [ 3  4  6 29]
          [ 3  4  2 17]
          [ 1  0  0  1]
          [ 0  0  1  3]])


In [3]:
def rosenbrock(x0, x1) :
    y = 100 * (x1 - x0 ** 2) ** 2 + (x0 - 1) ** 2
    return y

x0 = Variable(np.array(0.0))
x1 = Variable(np.array(2.0))

y = rosenbrock(x0, x1)
y.backward()
print(x0.grad, x1.grad)

variable(-2.0) variable(400.0)


In [4]:
x0 = Variable(np.array(0.0))
x1 = Variable(np.array(2.0))

iters = 100000
lr = 0.001

for i in range(iters) :
    y = rosenbrock(x0, x1)
    
    x0.cleargrad()
    x1.cleargrad()
    
    y.backward()
    
    x0.data -= lr * x0.grad.data
    x1.data -= lr * x1.grad.data
    
print(x0, x1)

variable(0.999999999999928) variable(0.9999999999998557)
